
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, FileImage, FileText } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  roomId: string;
}

export function ExportModal({ isOpen, onClose, roomId }: ExportModalProps) {
  const exportAsText = async () => {
    try {
      const { data: stickyNotes } = await supabase
        .from('sticky_notes')
        .select('*')
        .eq('room_id', roomId)
        .order('votes', { ascending: false });

      const { data: textElements } = await supabase
        .from('text_elements')
        .select('*')
        .eq('room_id', roomId);

      let content = `BRAINSTORMING SESSION - Room ${roomId}\n`;
      content += `Generated on: ${new Date().toLocaleString()}\n\n`;

      if (stickyNotes && stickyNotes.length > 0) {
        content += "STICKY NOTES (sorted by votes):\n";
        content += "=" .repeat(40) + "\n\n";
        
        stickyNotes.forEach((note, index) => {
          content += `${index + 1}. ${note.content || '(Empty note)'}\n`;
          content += `   👤 ${note.created_by} | ❤️ ${note.votes} votes | 🎨 ${note.color}\n\n`;
        });
      }

      if (textElements && textElements.length > 0) {
        content += "TEXT ELEMENTS:\n";
        content += "=" .repeat(40) + "\n\n";
        
        textElements.forEach((element, index) => {
          content += `${index + 1}. ${element.content || '(Empty text)'}\n`;
          content += `   👤 ${element.created_by}\n\n`;
        });
      }

      // Download as text file
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `brainstorming-${roomId}-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Export successful",
        description: "Text summary has been downloaded",
      });
      
    } catch (error) {
      console.error('Export failed:', error);
      toast({
        title: "Export failed",
        description: "There was an error exporting the session",
        variant: "destructive"
      });
    }
  };

  const exportAsImage = async () => {
    try {
      // Create a more comprehensive image export
      const canvas = document.createElement('canvas');
      canvas.width = 1200;
      canvas.height = 800;
      const ctx = canvas.getContext('2d');
      
      if (ctx) {
        // Background
        ctx.fillStyle = '#f9fafb';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // Header
        ctx.fillStyle = '#000';
        ctx.font = 'bold 32px Arial';
        ctx.textAlign = 'center';
        ctx.fillText(`Brainstorming Session - Room ${roomId}`, canvas.width / 2, 50);
        
        ctx.font = '18px Arial';
        ctx.fillText(new Date().toLocaleString(), canvas.width / 2, 80);
        
        // Get data
        const { data: stickyNotes } = await supabase
          .from('sticky_notes')
          .select('*')
          .eq('room_id', roomId)
          .order('votes', { ascending: false });

        // Draw sticky notes representation
        let yPos = 120;
        if (stickyNotes && stickyNotes.length > 0) {
          ctx.font = 'bold 24px Arial';
          ctx.textAlign = 'left';
          ctx.fillText('Sticky Notes:', 50, yPos);
          yPos += 40;
          
          ctx.font = '16px Arial';
          stickyNotes.slice(0, 10).forEach((note, index) => {
            // Draw note background
            ctx.fillStyle = note.color === 'yellow' ? '#fef3c7' : 
                           note.color === 'blue' ? '#dbeafe' :
                           note.color === 'green' ? '#d1fae5' : '#fef3c7';
            ctx.fillRect(50, yPos - 15, canvas.width - 100, 30);
            
            // Draw note text
            ctx.fillStyle = '#000';
            const text = note.content || '(Empty note)';
            ctx.fillText(`${index + 1}. ${text.substring(0, 80)}${text.length > 80 ? '...' : ''}`, 60, yPos + 5);
            ctx.fillText(`   by ${note.created_by} • ${note.votes} votes`, 60, yPos + 25);
            yPos += 50;
          });
        }

        // Add watermark
        ctx.font = '14px Arial';
        ctx.fillStyle = '#666';
        ctx.textAlign = 'center';
        ctx.fillText('Generated by Solid - Zero-friction brainstorming', canvas.width / 2, canvas.height - 20);
      }

      canvas.toBlob((blob) => {
        if (blob) {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `brainstorming-${roomId}-${Date.now()}.png`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
          
          toast({
            title: "Export successful",
            description: "Image has been downloaded",
          });
        }
      });
    } catch (error) {
      console.error('Image export failed:', error);
      toast({
        title: "Export failed",
        description: "There was an error exporting the image",
        variant: "destructive"
      });
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Export Brainstorming Session</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <Button
            onClick={exportAsText}
            className="w-full flex items-center space-x-2"
            variant="outline"
          >
            <FileText className="h-4 w-4" />
            <span>Export as Text Summary</span>
          </Button>
          
          <Button
            onClick={exportAsImage}
            className="w-full flex items-center space-x-2"
            variant="outline"
          >
            <FileImage className="h-4 w-4" />
            <span>Export as Image</span>
          </Button>
          
          <p className="text-sm text-gray-500">
            Text export includes all sticky notes (sorted by votes) and text elements. 
            Image export creates a visual summary of the session.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
